database:
  username: gin_chat
  password: gin_chat
  host: 192.168.88.130
  port: 3306
  dbname: gin_chat
  charset: utf8mb4
  parseTime: true
  loc: Local

redis:
  addr: 192.168.88.130:6379
  password: 123321
  db: 5
  poolSize: 30
  minIdleConn: 30