info:
  contact: {}
paths:
  /index:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - example
  /user/getUserBasicList:
    get:
      responses:
        "200":
          description: code", "message"}
          schema:
            type: string
      tags:
      - example
swagger: "2.0"
